# Generated by Django 5.2 on 2025-10-31 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('tasks', models.TextField(blank=True, help_text='Daily to-do list')),
                ('reflection', models.TextField(blank=True)),
                ('mood', models.CharField(choices=[('happy', 'Happy'), ('ok', 'OK'), ('sad', 'Sad'), ('stressed', 'Stressed')], default='ok', max_length=20)),
                ('ai_feedback', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
