# Generated by Django 5.2 on 2025-10-31 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyentry',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='dailyentry',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='dailyentry',
            name='date',
            field=models.DateField(auto_now_add=True, unique=True),
        ),
        migrations.AlterField(
            model_name='dailyentry',
            name='tasks',
            field=models.TextField(blank=True),
        ),
        migrations.RemoveField(
            model_name='dailyentry',
            name='user',
        ),
    ]
