# Generated by Django migration system

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_dailyentry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyentry',
            name='question_1_answer',
            field=models.TextField(blank=True, help_text='What went well today?'),
        ),
        migrations.AddField(
            model_name='dailyentry',
            name='question_2_answer',
            field=models.TextField(blank=True, help_text='What challenged you today?'),
        ),
        migrations.AddField(
            model_name='dailyentry',
            name='question_3_answer',
            field=models.TextField(blank=True, help_text='What would you improve tomorrow?'),
        ),
        migrations.AddField(
            model_name='dailyentry',
            name='goals',
            field=models.TextField(blank=True, help_text='Your goals for today or this week'),
        ),
        migrations.AlterModelOptions(
            name='dailyentry',
            options={'ordering': ['-date'], 'verbose_name': 'Daily Entry', 'verbose_name_plural': 'Daily Entries'},
        ),
    ]
